# these are dev properties and will be overwritten by k8s env vars
FRONTEND_URL: https://development.bloglog.io
DATASTORE_URL: https://development.bloglog.io/api/v1/datastore
EXTRACTOR_URL: https://development.bloglog.io/api/v1/extractor
PROCESSOR_URL: https://development.bloglog.io/api/v1/processor
SEARCHER_URL: https://development.bloglog.io/api/v1/searcher
WEBHOOK_URL: https://development.bloglog.io/api/v1/webhook